### ISSUE TITLE
Pre-built binaries missing for Linux in the Odin bindings 

### ISSUE THREAD

**Issue by Valnir17** [nicbarker/clay#11]
Trying to build an example outputs:

cannot find -l "[pathtoclay]/clay/bindings/odin/clay-odin//linux/libclay.a"

**Comment by nicbarker** [comment]
Thanks for the heads up, somehow managed to forget to build the linux lib. Would you be able to test it out for me if I push the file? I don't have access to a linux box at the moment 🙂

**Comment by nicbarker** [comment]
I've pushed the linux lib, please let me know if it works for you!

**Comment by Valnir17** [comment]
It did, thanks!

**Comment by nicbarker** [comment]
Awesome, good to hear!
