### ISSUE TITLE
[Compilation] `Clay_PointerOver` only defined in implementation

### ISSUE THREAD

**Issue by Mathys-Gasnier** [nicbarker/clay#117]
The function `Clay_PointerOver` is defined in the implementation part of `clay.h` but not in the header part.
Since this is not mentioned on the doc, I assume it was forgotten.

**Comment by nicbarker** [comment]
Hello, yes you're 100% right, that is a mistake. Will fix it now 👍

**Comment by nicbarker** [comment]
Fixed here: https://github.com/nicbarker/clay/commit/37af99b221314d5d6d83c7bfcf6af433a57d5450

**Comment by Mathys-Gasnier** [comment]
Yep, it works. Thanks for the quick fix
