### ISSUE TITLE
Remove capacity field from array types.

### ISSUE THREAD

**Issue by Zettexe** [nicbarker/clay#137]
As I am working on zig bindings for Clay I notice that array types are defined to have a redundant capacity field. As far as I can tell tell this is just a value copy of the maximum amount of items in most cases. 

If this does get removed I can cleanly convert between Clay's array types and zig's built in slice type making for a nicer development experience and if someone really does need the capacity they can get it from the arena.

**Comment by raugl** [comment]
Looking at the code, there are only two struct in the public api that have a `capacity` field. One is `Clay_Arena` which makes great use of it, and which is also more complex than just a simple slice. The other one is `Clay_RenderCommandArray` which also uses it.

The other thing to keep in mind is that even it they got removed, you still wouldn't be able to implement what you want. In zig slices have no guaranteed in-memory representation, so you can't export functions that have slices in their signature.

As for a solution, it's easy enough to write wrapper functions around clay's api that convert `[]const u8` to and from `Clay_String`. You can add the conversion functions as members so it's super easy to use:
```zig
pub const String = extern struct {
    len: usize,
        chars: [*c]const u8,

        pub fn init(string: []const u8) String {
        return String{ .chars = string.ptr, .len = string.len };
    }
    pub fn slice(self: String) []const u8 {
        return self.chars[0..self.len];
    }
};
```
And for `Clay_RenderCommandArray` which we need to iterate over in the renderers, it's easy enough to write `render_commands.slice()`:
```zig
pub const RenderCommandArray = extern struct {
    capacity: u32,
        len: u32,
        items: [*c]RenderCommand,

    pub fn slice(self: RenderCommandArray) []RenderCommand {
        return self.items[0..self.len];
    }
};
```

**Comment by Zettexe** [comment]
Yes I agree, I am not advocating for the removal of capacity on Clay_Arena and im not sure why I thought this was needed in the first place. Chalk it up to a tired morning I guess.
