### ISSUE TITLE
Not building on Windows

### ISSUE THREAD

**Issue by 0xeb** [nicbarker/clay#14]
After I configure CMake for example: `cmake -B build . -A x64` on Windows and it picks up VS2022, I get the first error complaining about the added switch `-Wno-initializer-overrides`.
After removing that switch, I get many compilation errors later on.

Is this supposed to build on Windows?

I try switching to `clang` with:

```bash
cmake -B build . -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
```

Also, to no avail.

It builds on Linux though.

**Comment by nicbarker** [comment]
Hello, sorry to hear things aren't working for you. To get a little more detail, are you trying to build the examples in the repo with the root `CMakeLists.txt`?

**Comment by 0xeb** [comment]
Yes, correct. Configuring from the root. As I said, the same steps work on Ubuntu 24

**Comment by nicbarker** [comment]
Thanks, what version of clang on windows are you using?

**Comment by nicbarker** [comment]
For context in terms of what I'm trying to figure out - I'm able to build the examples with CLion + Cmake + Clang 18 on Windows 10

**Comment by 0xeb** [comment]
```
C:\Program Files\Microsoft Visual Studio\2022\Professional>clang --version
clang version 17.0.3
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\x64\bin

C:\Program Files\Microsoft Visual Studio\2022\Professional>

```

**Comment by nicbarker** [comment]
Interesting, would you be able to paste the whole output of the compile that fails?

**Comment by 0xeb** [comment]
Most Windows users don't use CLion . Either VS community edition, VS Pro, VS Code, etc.

Can you try with VS community edition 2022?

**Comment by 0xeb** [comment]
Ok, I figured it out.

It turned out the way I was configuring CMake on Windows was still picking 'cl' instead of 'clang-cl'.

The proper way to fix this in Windows, is to configure as such:

```
cmake -B build -T ClangCL

```

- Note the `-T` to select the proper toolchain.

Cheers and thanks for your help!

**Comment by nicbarker** [comment]
No worries, and I'll make sure that I make a note of that somewhere - it's always good to collect platform specific compiler quirks! 🙂
