### ISSUE TITLE
[Bug] Can't Include clay.h in Multiple Translation Units

### ISSUE THREAD

**Issue by mikejsavage** [nicbarker/clay#19]
Normally single header libs look like

```cpp
void f();

#if LIB_IMPLEMENTATION
void f() { }
#endif 
```

so you can include the header in multiple files and not get multiple definition errors.

In clay you have

```cpp
#if HEADER_GUARD
void f() { }
#endif 
```

so there's no way to get the API declarations without their implementations, so if you include clay.h from multiple files it won't link

**Comment by nicbarker** [comment]
Hello, thanks for the report! This one is my fault, I only use a single translation unit in my projects and just forgot to declare the function prototypes. Will get this fixed for you today.

**Comment by nicbarker** [comment]
This should be fixed by https://github.com/nicbarker/clay/pull/20, please let me know if it works for you!

**Comment by nicbarker** [comment]
@mikejsavage apologies, I didn't have a correct setup going to catch some of the issues. I've addressed the ones I can see in https://github.com/nicbarker/clay/commit/5bb725d0057155200db13890a86922d393305167
