### ISSUE TITLE
[Feature Request] MSVC support

### ISSUE THREAD

**Issue by mikejsavage** [nicbarker/clay#22]
Clay currently doesn't compile under MSVC because:

1. It doesn't support C designated initializers
2. It doesn't support `__attribute__((packed))__`
3. It doesn't like `CLAY__ALIGNMENT`, `#define CLAY__ALIGNMENT(type) _Alignof(type)` works though

1 and 2 are not very nice to solve with Microsoft flavoured C, although I will say all of these have direct solutions if you don't mind C++

**Comment by nicbarker** [comment]
Thanks for opening this one! I had been putting it off until the core implementation stabilized, but we can definitely begin to address each of these

> It doesn't support C designated initializers
AFAIK there should be a way at the very least for the library syntax to be compatible with both C99 designated initializers as well as C++20 designated initializers. C++20 is much more picky but should be roughly syntax equivalent if the members are in declaration order

> It doesn't support __attribute__((packed))__
Yep nice, should be able to replace this with a `#ifdef` of msvc and swap out for whatever equivalent to size enums into 1 byte

> It doesn't like CLAY__ALIGNMENT, #define CLAY__ALIGNMENT(type) _Alignof(type) works though
This one should be reasonably easy to `#ifdef` in as well.

As for supporting non C99 versions of C, the best way forward might be to compile clay as a lib and write a second set of macros / declarations that are compatible with C11 etc... 🤔

**Comment by nicbarker** [comment]
From my investigations so far, it looks like I'm probably going to be able to get it in line with MSVC C++20. Microsoft flavoured C though, might not be possible. I don't think I'm willing to drop to C89 for the whole library just to support those versions on MSVC. Probably would be best in that case to just compile as a lib and link in 👍

**Comment by nicbarker** [comment]
Follow up: Successfully compiling as C++20 with MSVC here https://github.com/nicbarker/clay/actions/runs/11083013067/job/30796749136 😁

**Comment by nicbarker** [comment]
I'm going to mark this as completed for now, when clay stabilizes a little more we can reopen a discussion into whether it's worth dropping to C89 for the library itself in order to support C11 and beyond 🙂

**Comment by mikejsavage** [comment]
Yep I've been messing with clay in our engine, it seems fine so far but I haven't done much with it yet

**Comment by nicbarker** [comment]
@mikejsavage Great, please let me know if you end up building something with it!

**Comment by nicbarker** [comment]
@MiraiMindz thanks for reaching out 🙂
The main reason for not dropping to ansi C at this point is that the quality of life features in C99 really make building and changing code so much easier (for me), specifically variadic macros, anywhere declarations and designated initializers.
I'm definitely keeping the option open for when the library stabilizes to just bug fixes & platform specific changes (which I intend to happen eventually) but for now I think it will make dev a little too difficult for me. Sorry if this wasn't the answer you were after, but of course feel free to adapt the core parts of the lib for your own use.

**Comment by nicbarker** [comment]
@namandixit that is very interesting, I'll have to review and see how close we are or what the specific problems are. It's possible that by getting to c++20 support I actually got closer to msvc C11 / C17 than I realised.

**Comment by Robert-M-Muench** [comment]
I'm just trying to compile with MSVC as well and face the same problems. To use packing attributes, they need to be specified in the correct syntax and position:

1. For MSVC (Microsoft Visual C++), packing must be specified using pragma directives before and after the enum:
```Cpp
#pragma pack(push, 1)
typedef enum {  // No identifier needed here
    // enum values...
} Clay__ElementConfigType;
#pragma pack(pop)
```

2. For GCC/Clang, the attribute must be specified using the correct attribute syntax:
```Cpp
typedef enum __attribute__((packed)) {  // Attribute goes here, not an identifier
    // enum values...
} Clay__ElementConfigType;
```
If you want to create a cross-platform solution, you would typically define a macro that expands to the appropriate syntax based on the compiler:

```Cpp
#ifdef _MSC_VER
    #define CLAY_PACKED_ENUM
    #define CLAY_PACK_BEGIN #pragma pack(push, 1)
    #define CLAY_PACK_END #pragma pack(pop)
#else
    #define CLAY_PACKED_ENUM __attribute__((packed))
    #define CLAY_PACK_BEGIN
    #define CLAY_PACK_END
#endif
```

Then you could use it like this:
```Cpp
CLAY_PACK_BEGIN
typedef enum CLAY_PACKED_ENUM {
    // enum values...
} Clay__ElementConfigType;
CLAY_PACK_END
```

Maybe this can be somehow added/handled via a generator as well.

But, what to do until then?

**Comment by FintasticMan** [comment]
I've implemented this based on feedback in #118.

**Comment by Robert-M-Muench** [comment]
Yes, sorry, I saw it now. 

I am looking forward to getting it merged into the master. Will wait so long.

**Comment by codewithpapakwame** [comment]
## ERRor
Bro I am facing the same problem hope we can fix this now

**Comment by vulcan-dev** [comment]
+1

I'm currently using C++20 and clang-cl, but clang-cl has some issues and prevents me from compiling a static library (not related with clay), so MSVC support would be great

**Comment by nicbarker** [comment]
As of https://github.com/nicbarker/clay/pull/178 merging, we should have decent MSVC support across the board, including for C99, C11 and C23 via MSVC 🙂
Please reach out or open a new issue if there are any other problems!
