### ISSUE TITLE
Create a discord server

### ISSUE THREAD

**Issue by SaptakBhoumik** [nicbarker/clay#35]
I think a discord server will be useful so that people can discuss among themselves if they face any issue. This is much better than creating issues on github

**Comment by nicbarker** [comment]
I agree, I have been meaning to create one for some time 🙂
One thing I just want to make sure of is that useful information and answers to questions are still available publicly and indexable by google, for people who aren't using / don't want to use discord. Perhaps a FAQ section or similar that I'll maintain from time to time.

**Comment by nicbarker** [comment]
Link to discord is here: https://discord.gg/b4FTWkxdvT

**Comment by SaptakBhoumik** [comment]
Thanks
