### ISSUE TITLE
[BUG] elements with fixed size between elements with grow size 

### ISSUE THREAD

**Issue by SogoCZE** [nicbarker/clay#38]
When we have three elements in a row with widths:
- grow
- fixed (200)
- grow

Layout behaves incorrectly. Two grow-width elements should have the same width - they should be half of what is left of the parent's available width after subtracting the fixed-width element. Currently, the third element is larger than the first.

Clay result:
![image](https://github.com/user-attachments/assets/63294024-38f1-4cb0-a638-01f1f1f12e11)

CSS result:
![image](https://github.com/user-attachments/assets/74b43470-5082-4846-86ae-50dc76bf2b3a)

**Comment by nicbarker** [comment]
Thanks for the report, will look into getting this fixed today 👍

**Comment by nicbarker** [comment]
I'm reasonably sure this fixes the issue: [26013e6](https://github.com/nicbarker/clay/commit/26013e657fee1514798b799ed9bcfac56e2a036b). Please test it out when you get a chance and let me know 🙂

**Comment by SogoCZE** [comment]
it's definitely better than it was, but the last element is always a little bigger than it should be, and the first is smaller (by a few pixels, e.g. 5).

For example, if I have a container 600 pixels wide with elements:
- grow
- fixed (200)
- grow

they should all be exactly 200 pixels wide. However, the first has 197 and the third has 202.

**Comment by nicbarker** [comment]
This has been confirmed as fixed here: 🙂
https://github.com/nicbarker/clay/commit/9a8775751f54a289e16b79d803ff69d00bd285d5
