### ISSUE TITLE
[Bug] Touch scrolling disabled on official website example

### ISSUE THREAD

**Issue by johan0A** [nicbarker/clay#40]
Scrolling does not work on the clay site on the android version of firefox and chrome. Trying to swipe up to scroll simply does nothing.

android 14
chrome 129.0.6668.82
firefox 131.0.2

**Comment by SogoCZE** [comment]
This is also broken on iOS (chrome and safari).

**Comment by nicbarker** [comment]
Thanks for reporting this one, silly mistake on my part. Fixed with a tiny one liner here:
https://github.com/nicbarker/clay/commit/4ce3105f588310fd09143a2c831eda48f07dbbc5
Going to put in some automated testing at some point to catch this kind of thing 😅

**Comment by SogoCZE** [comment]
Tested on iOS chrome and its working now!
