### ISSUE TITLE
Include Path Issues (C++)

### ISSUE THREAD

**Issue by Anthony-J-G** [nicbarker/clay#61]
This is a relatively minor issue and I'm sure I'll find a work around, but more so just wanted to let you know of the use case regardless. I've been building a small sample to play around with Clay in C++ using Zig as the build system and I kept running into a weird error that was driving me crazy for awhile. 

With Zig, fetching dependencies is fairly trivial, just tell it to fetch a link and then point it at the right files and you are good to go. Apparently because of a header inside of the C++ stdlib `#include <version>` and the `VERSION` file at the root of this repository, a compilation conflict was happening in my include paths (namely including the root of this repo to ensure `clay.h` is in my path). Was wondering if in the GitHub releases you could also have one with the header nested inside of an `include/` directory or something to side step this? I could see it being an issue in CMake as well.

Either way, the framework seems super cool, and excited to keep working with it!

**Comment by nicbarker** [comment]
That's interesting, the VERSION file is not necessary by any means, would it help if I just deleted it?

**Comment by Anthony-J-G** [comment]
Deleting the file would for sure solve the problem because of the way clang handles include paths. The only other foreseeable problem would be if another conflicting file gets added to the project root, but that seems like a rare edge case.

For the moment I just have `clay.h` copy pasted into my own project structure, but having access to Zig/CMake automating it also makes fetching things like the license or other important informational files.

**Comment by nicbarker** [comment]
Great, I'll delete the VERSION - it doesn't need to be there 🙂

**Comment by nicbarker** [comment]
Ok done, let me know if it fixes it for you!

**Comment by Anthony-J-G** [comment]
Works like a charm, thank you so much!! All the include paths resolve properly with no collisions/redefinition.

**Comment by nicbarker** [comment]
Great!
