### ISSUE TITLE
[Windows11/MSYS2 - LLVM/CLANG] .height = CLAY_SIZING_GROW() expected expression.

### ISSUE THREAD

**Issue by MiraiMindz** [nicbarker/clay#62]
I'm following the YouTube Video [https://www.youtube.com/watch?v=DYWTw19_8r4](https://www.youtube.com/watch?v=DYWTw19_8r4), and on the first example of creating a red window, I can't compile the program with CMAKE and LLVM/CLANG.

here is the code I'm running:

```c
Clay_Raylib_Initialize(GetScreenWidth(), GetScreenHeight(), "Example" , FLAG_WINDOW_RESIZABLE);
    uint32_t clayRequiredMemory = Clay_MinMemorySize();
    Clay_Arena clayMemory = (Clay_Arena){
        .memory = malloc(clayRequiredMemory),
        .capacity = clayRequiredMemory,
    };

    Clay_Initialize(clayMemory, (Clay_Dimensions){
        .width = GetScreenWidth(),
        .height = GetScreenHeight(),
    });


    while (!WindowShouldClose()) {
        Clay_BeginLayout();
        /* START UI Hierarchy here */

        CLAY(
            CLAY_RECTANGLE({ .color = {255, 0, 0, 255} }),
            CLAY_LAYOUT({
                .sizing = {
                    .width = CLAY_SIZING_GROW(),
                    .height = CLAY_SIZING_GROW(),
                }
            })
        ) {};

        /* END UI Hierarchy here */
        Clay_RenderCommandArray renderCommands = Clay_EndLayout();
        BeginDrawing();
        ClearBackground(WHITE);
        Clay_Raylib_Render(renderCommands);
        EndDrawing();
    }
```

and I'm getting:

```
{PROGRAM_FILE}: error: expected expression
  310 |                     .width = CLAY_SIZING_GROW(),
      |                              ^
{PROGRAM_FILE}: note: expanded from macro 'CLAY_SIZING_GROW'
   76 | #define CLAY_SIZING_GROW(...) CLAY__SIZING_GROW_INTERNAL(CLAY__STRUCT_OVERRIDE("empty", ##__VA_ARGS__, CLAY__STRUCT_1_ARGS, CLAY__STRUCT_0_ARGS)(__VA_ARGS__))
      |                               ^
{PROGRAM_FILE}: note: expanded from macro 'CLAY__SIZING_GROW_INTERNAL'
   75 | #define CLAY__SIZING_GROW_INTERNAL(...) CLAY__INIT(Clay_SizingAxis) { .sizeMinMax = CLAY__INIT(Clay_SizingMinMax) __VA_ARGS__, .type = CLAY__SIZING_TYPE_GROW }
      |                                                                                                                              ^
{PROGRAM_FILE}: error: expected expression
  311 |                     .height = CLAY_SIZING_GROW(),
      |                               ^
{PROGRAM_FILE}: note: expanded from macro 'CLAY_SIZING_GROW'
   76 | #define CLAY_SIZING_GROW(...) CLAY__SIZING_GROW_INTERNAL(CLAY__STRUCT_OVERRIDE("empty", ##__VA_ARGS__, CLAY__STRUCT_1_ARGS, CLAY__STRUCT_0_ARGS)(__VA_ARGS__))
      |                               ^
{PROGRAM_FILE}: note: expanded from macro 'CLAY__SIZING_GROW_INTERNAL'
   75 | #define CLAY__SIZING_GROW_INTERNAL(...) CLAY__INIT(Clay_SizingAxis) { .sizeMinMax = CLAY__INIT(Clay_SizingMinMax) __VA_ARGS__, .type = CLAY__SIZING_TYPE_GROW }
      |                                                                                                                              ^
2 errors generated.
```

There are my compiling options: `-O3 -march=native -std=c99 -w -finput-charset=UTF-8 -fexec-charset=UTF-8``

> FYI: I can compile and run a program with RayLib and RayGUI just fine, the issue is only with CLAY.

I'm using Windows 11 with MSYS2, I'll test this issue in a Linux VM too to see if it's a Windows(tm) only issue.

**Comment by nicbarker** [comment]
Interesting, code looks fine to me - would you be able to try using CMake to compile the `raylib-sidebar-scrolling-container` and see if you get the same issue?

**Comment by MiraiMindz** [comment]
![image](https://github.com/user-attachments/assets/34aa6cde-36fd-4aad-94d6-8a0a743681c6)

It compiled just fine, I'll take a look in the source of the example to see if there is something between it and my code in order to fix the issue.

btw these where the compile commands I've used:

`cmake -G "MinGW Makefiles" -S . -B {full_path}\raylib-sidebar-scrolling-container\build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_C_COMPILER="C:/msys64/mingw64/bin/clang.exe" -DCMAKE_CXX_COMPILER="C:/msys64/mingw64/bin/clang++.exe"`

`cmake --build build --parallel {number of cores}`

**Comment by MiraiMindz** [comment]
Ok, I've figured it out, the code will **not** compile if you pass `-std=c99` (strict C99) to the compiler, but it **will** compile if you pass `-std=gnu99` (C99 with GNU extensions), this is probably your code use some GNU extensions.

When I have time, I'll make a pull-request with some changes (and code docs of course to help with understanding of strict c89), to make this lib *compiler agnostic* (and version agnostic) because some compilers may or may not implement GNU extensions.

closing this issue.

**Comment by MiraiMindz** [comment]
Ok, I've figured it out, the code will **not** compile if you pass `-std=c99` (strict C99) to the compiler, but it **will** compile if you pass `-std=gnu99` (C99 with GNU extensions), this is probably your code use some GNU extensions.

When I have time, I'll make a pull-request with some changes (and code docs of course to help with understanding of strict c89), to make this lib *compiler agnostic* (and version agnostic) because some compilers may or may not implement GNU extensions.

closing this issue.

**Comment by nicbarker** [comment]
Thank you for investigating, really appreciate it. We can take a look at these incompatibilities over the next few weeks 🙂
