### ISSUE TITLE
Delphi Bindings

### ISSUE THREAD

**Issue by jarroddavis68** [nicbarker/clay#85]
Just discovered this project, working on Delphi bindings. The main issue is the C macros. Alot of them are difficult to convert to Delphi code. Any suggestions? Or are there Pascal bindings that exist already maybe?

**Comment by nicbarker** [comment]
@jarroddavis68 how did you go with this one?

**Comment by jarroddavis68** [comment]
I didn't. The macros are a problem for use in Delphi.

**Comment by nicbarker** [comment]
Ah I see. Yeah to use Clay in an ergonomic way, bindings to other languages need to recreate the macros using their own in language constructs.

If you take a look at the odin bindings (odin doesn't support macros) - you can get an idea of how it's used in other languages:

https://github.com/nicbarker/clay/blob/main/bindings/odin/clay-odin/clay.odin
