### ISSUE TITLE
[Bindings] Rust

### ISSUE THREAD

**Issue by EmmanuelMess** [nicbarker/clay#94]
I have no idea how rust crates work, but I would love to have bindings for rust.

**Comment by FintasticMan** [comment]
See https://github.com/clay-ui-rs/clay :-)

**Comment by nicbarker** [comment]
We will add a link out to the above repo when the authors are happy with where they are up to 👍

**Comment by emoon** [comment]
First version has been released https://crates.io/crates/clay-layout notice it still lacks documentation, examples and (more) tests. There is a basic test there that shows how it can be used, but needs to be expanded.

**Comment by nicbarker** [comment]
I am going to close this as done for now, thanks to the amazing work of @emoon and others, we can reopen others if there are additional things that need fixing 👍

**Comment by rectalogic** [comment]
I built Rust bindings, just as an experiment to learn Rust (not intended for actual use...).
Also a clay renderer based on macroquad.
https://github.com/rectalogic/clay-rs

Recreation of the clay intro video app here https://github.com/rectalogic/clay-rs/blob/main/clay-renderer-macroquad/examples/introducing-clay-video-demo.rs
(macroquad doesn't support rounded rects or expose scissor/clipping - and there are some other rendering issues...)
